FROM public.ecr.aws/lambda/python:3.12

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/var/task

RUN dnf install -y tar xz && dnf clean all
RUN curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o /tmp/ffmpeg.tar.xz \
    && mkdir -p /opt/ffmpeg \
    && tar -xJf /tmp/ffmpeg.tar.xz --strip-components=1 -C /opt/ffmpeg \
    && ln -s /opt/ffmpeg/ffmpeg /usr/bin/ffmpeg \
    && ln -s /opt/ffmpeg/ffprobe /usr/bin/ffprobe \
    && rm /tmp/ffmpeg.tar.xz

COPY apps/worker/requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY apps/worker/ ${LAMBDA_TASK_ROOT}/

CMD ["aws_lambda_handler.handler"]
