create extension if not exists pgcrypto with schema extensions;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.video_jobs (
  id text primary key,
  user_id text not null,
  original_filename text not null,
  video_path text not null,
  storage_bucket text not null default 'videos',
  upload_content_type text not null default 'application/octet-stream',
  upload_file_size integer not null default 0,
  status text not null default 'pending_upload',
  current_step text not null default 'awaiting_upload',
  progress integer not null default 0,
  error_message text not null default '',
  processing_started_at timestamptz,
  preprocessing_metadata jsonb not null default '{}'::jsonb,
  artifact_paths jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_video_jobs_user_id on public.video_jobs (user_id);

create table if not exists public.video_caption_results (
  id bigint generated by default as identity primary key,
  job_id text not null unique references public.video_jobs (id) on delete cascade,
  neutral_summary text not null default '',
  formal_caption text not null default '',
  sarcastic_caption text not null default '',
  humorous_tech_caption text not null default '',
  humorous_non_tech_caption text not null default '',
  raw_pipeline_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

drop trigger if exists set_video_jobs_updated_at on public.video_jobs;
create trigger set_video_jobs_updated_at
before update on public.video_jobs
for each row
execute function public.set_updated_at();

